/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TutorialsRouteImport } from './routes/tutorials'
import { Route as TermsOfServiceRouteImport } from './routes/terms-of-service'
import { Route as SupportRouteImport } from './routes/support'
import { Route as SubscriptionRouteImport } from './routes/subscription'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as RoadmapRouteImport } from './routes/roadmap'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as PricingCheckoutRouteImport } from './routes/pricing-checkout'
import { Route as LogInRouteImport } from './routes/log-in'
import { Route as GettingStartedRouteImport } from './routes/getting-started'
import { Route as ContactUsRouteImport } from './routes/contact-us'
import { Route as CheckEmailRouteImport } from './routes/check-email'
import { Route as BuilderRouteImport } from './routes/builder'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AboutUsRouteImport } from './routes/about-us'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiSubscriptionRouteImport } from './routes/api/subscription'
import { Route as ApiReconcileCheckoutRouteImport } from './routes/api/reconcile-checkout'
import { Route as ApiPortalSessionRouteImport } from './routes/api/portal-session'
import { Route as ApiCheckoutRouteImport } from './routes/api/checkout'
import { Route as ApiCancelSubscriptionRouteImport } from './routes/api/cancel-subscription'
import { Route as AccountBillingRouteImport } from './routes/account.billing'
import { Route as ApiWebhooksStripeRouteImport } from './routes/api/webhooks/stripe'

const TutorialsRoute = TutorialsRouteImport.update({
  id: '/tutorials',
  path: '/tutorials',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsOfServiceRoute = TermsOfServiceRouteImport.update({
  id: '/terms-of-service',
  path: '/terms-of-service',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscriptionRoute = SubscriptionRouteImport.update({
  id: '/subscription',
  path: '/subscription',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapRoute = RoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingCheckoutRoute = PricingCheckoutRouteImport.update({
  id: '/pricing-checkout',
  path: '/pricing-checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const LogInRoute = LogInRouteImport.update({
  id: '/log-in',
  path: '/log-in',
  getParentRoute: () => rootRouteImport,
} as any)
const GettingStartedRoute = GettingStartedRouteImport.update({
  id: '/getting-started',
  path: '/getting-started',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactUsRoute = ContactUsRouteImport.update({
  id: '/contact-us',
  path: '/contact-us',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckEmailRoute = CheckEmailRouteImport.update({
  id: '/check-email',
  path: '/check-email',
  getParentRoute: () => rootRouteImport,
} as any)
const BuilderRoute = BuilderRouteImport.update({
  id: '/builder',
  path: '/builder',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutUsRoute = AboutUsRouteImport.update({
  id: '/about-us',
  path: '/about-us',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSubscriptionRoute = ApiSubscriptionRouteImport.update({
  id: '/api/subscription',
  path: '/api/subscription',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReconcileCheckoutRoute = ApiReconcileCheckoutRouteImport.update({
  id: '/api/reconcile-checkout',
  path: '/api/reconcile-checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPortalSessionRoute = ApiPortalSessionRouteImport.update({
  id: '/api/portal-session',
  path: '/api/portal-session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCheckoutRoute = ApiCheckoutRouteImport.update({
  id: '/api/checkout',
  path: '/api/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCancelSubscriptionRoute = ApiCancelSubscriptionRouteImport.update({
  id: '/api/cancel-subscription',
  path: '/api/cancel-subscription',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountBillingRoute = AccountBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AccountRoute,
} as any)
const ApiWebhooksStripeRoute = ApiWebhooksStripeRouteImport.update({
  id: '/api/webhooks/stripe',
  path: '/api/webhooks/stripe',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/account': typeof AccountRouteWithChildren
  '/blog': typeof BlogRoute
  '/builder': typeof BuilderRoute
  '/check-email': typeof CheckEmailRoute
  '/contact-us': typeof ContactUsRoute
  '/getting-started': typeof GettingStartedRoute
  '/log-in': typeof LogInRoute
  '/pricing-checkout': typeof PricingCheckoutRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/profile': typeof ProfileRoute
  '/roadmap': typeof RoadmapRoute
  '/sign-up': typeof SignUpRoute
  '/subscription': typeof SubscriptionRoute
  '/support': typeof SupportRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/tutorials': typeof TutorialsRoute
  '/account/billing': typeof AccountBillingRoute
  '/api/cancel-subscription': typeof ApiCancelSubscriptionRoute
  '/api/checkout': typeof ApiCheckoutRoute
  '/api/portal-session': typeof ApiPortalSessionRoute
  '/api/reconcile-checkout': typeof ApiReconcileCheckoutRoute
  '/api/subscription': typeof ApiSubscriptionRoute
  '/api/webhooks/stripe': typeof ApiWebhooksStripeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/account': typeof AccountRouteWithChildren
  '/blog': typeof BlogRoute
  '/builder': typeof BuilderRoute
  '/check-email': typeof CheckEmailRoute
  '/contact-us': typeof ContactUsRoute
  '/getting-started': typeof GettingStartedRoute
  '/log-in': typeof LogInRoute
  '/pricing-checkout': typeof PricingCheckoutRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/profile': typeof ProfileRoute
  '/roadmap': typeof RoadmapRoute
  '/sign-up': typeof SignUpRoute
  '/subscription': typeof SubscriptionRoute
  '/support': typeof SupportRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/tutorials': typeof TutorialsRoute
  '/account/billing': typeof AccountBillingRoute
  '/api/cancel-subscription': typeof ApiCancelSubscriptionRoute
  '/api/checkout': typeof ApiCheckoutRoute
  '/api/portal-session': typeof ApiPortalSessionRoute
  '/api/reconcile-checkout': typeof ApiReconcileCheckoutRoute
  '/api/subscription': typeof ApiSubscriptionRoute
  '/api/webhooks/stripe': typeof ApiWebhooksStripeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/account': typeof AccountRouteWithChildren
  '/blog': typeof BlogRoute
  '/builder': typeof BuilderRoute
  '/check-email': typeof CheckEmailRoute
  '/contact-us': typeof ContactUsRoute
  '/getting-started': typeof GettingStartedRoute
  '/log-in': typeof LogInRoute
  '/pricing-checkout': typeof PricingCheckoutRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/profile': typeof ProfileRoute
  '/roadmap': typeof RoadmapRoute
  '/sign-up': typeof SignUpRoute
  '/subscription': typeof SubscriptionRoute
  '/support': typeof SupportRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/tutorials': typeof TutorialsRoute
  '/account/billing': typeof AccountBillingRoute
  '/api/cancel-subscription': typeof ApiCancelSubscriptionRoute
  '/api/checkout': typeof ApiCheckoutRoute
  '/api/portal-session': typeof ApiPortalSessionRoute
  '/api/reconcile-checkout': typeof ApiReconcileCheckoutRoute
  '/api/subscription': typeof ApiSubscriptionRoute
  '/api/webhooks/stripe': typeof ApiWebhooksStripeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about-us'
    | '/account'
    | '/blog'
    | '/builder'
    | '/check-email'
    | '/contact-us'
    | '/getting-started'
    | '/log-in'
    | '/pricing-checkout'
    | '/privacy-policy'
    | '/profile'
    | '/roadmap'
    | '/sign-up'
    | '/subscription'
    | '/support'
    | '/terms-of-service'
    | '/tutorials'
    | '/account/billing'
    | '/api/cancel-subscription'
    | '/api/checkout'
    | '/api/portal-session'
    | '/api/reconcile-checkout'
    | '/api/subscription'
    | '/api/webhooks/stripe'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about-us'
    | '/account'
    | '/blog'
    | '/builder'
    | '/check-email'
    | '/contact-us'
    | '/getting-started'
    | '/log-in'
    | '/pricing-checkout'
    | '/privacy-policy'
    | '/profile'
    | '/roadmap'
    | '/sign-up'
    | '/subscription'
    | '/support'
    | '/terms-of-service'
    | '/tutorials'
    | '/account/billing'
    | '/api/cancel-subscription'
    | '/api/checkout'
    | '/api/portal-session'
    | '/api/reconcile-checkout'
    | '/api/subscription'
    | '/api/webhooks/stripe'
  id:
    | '__root__'
    | '/'
    | '/about-us'
    | '/account'
    | '/blog'
    | '/builder'
    | '/check-email'
    | '/contact-us'
    | '/getting-started'
    | '/log-in'
    | '/pricing-checkout'
    | '/privacy-policy'
    | '/profile'
    | '/roadmap'
    | '/sign-up'
    | '/subscription'
    | '/support'
    | '/terms-of-service'
    | '/tutorials'
    | '/account/billing'
    | '/api/cancel-subscription'
    | '/api/checkout'
    | '/api/portal-session'
    | '/api/reconcile-checkout'
    | '/api/subscription'
    | '/api/webhooks/stripe'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutUsRoute: typeof AboutUsRoute
  AccountRoute: typeof AccountRouteWithChildren
  BlogRoute: typeof BlogRoute
  BuilderRoute: typeof BuilderRoute
  CheckEmailRoute: typeof CheckEmailRoute
  ContactUsRoute: typeof ContactUsRoute
  GettingStartedRoute: typeof GettingStartedRoute
  LogInRoute: typeof LogInRoute
  PricingCheckoutRoute: typeof PricingCheckoutRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  ProfileRoute: typeof ProfileRoute
  RoadmapRoute: typeof RoadmapRoute
  SignUpRoute: typeof SignUpRoute
  SubscriptionRoute: typeof SubscriptionRoute
  SupportRoute: typeof SupportRoute
  TermsOfServiceRoute: typeof TermsOfServiceRoute
  TutorialsRoute: typeof TutorialsRoute
  ApiCancelSubscriptionRoute: typeof ApiCancelSubscriptionRoute
  ApiCheckoutRoute: typeof ApiCheckoutRoute
  ApiPortalSessionRoute: typeof ApiPortalSessionRoute
  ApiReconcileCheckoutRoute: typeof ApiReconcileCheckoutRoute
  ApiSubscriptionRoute: typeof ApiSubscriptionRoute
  ApiWebhooksStripeRoute: typeof ApiWebhooksStripeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tutorials': {
      id: '/tutorials'
      path: '/tutorials'
      fullPath: '/tutorials'
      preLoaderRoute: typeof TutorialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-of-service': {
      id: '/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/terms-of-service'
      preLoaderRoute: typeof TermsOfServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscription': {
      id: '/subscription'
      path: '/subscription'
      fullPath: '/subscription'
      preLoaderRoute: typeof SubscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmap': {
      id: '/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof RoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing-checkout': {
      id: '/pricing-checkout'
      path: '/pricing-checkout'
      fullPath: '/pricing-checkout'
      preLoaderRoute: typeof PricingCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/log-in': {
      id: '/log-in'
      path: '/log-in'
      fullPath: '/log-in'
      preLoaderRoute: typeof LogInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/getting-started': {
      id: '/getting-started'
      path: '/getting-started'
      fullPath: '/getting-started'
      preLoaderRoute: typeof GettingStartedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact-us': {
      id: '/contact-us'
      path: '/contact-us'
      fullPath: '/contact-us'
      preLoaderRoute: typeof ContactUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/check-email': {
      id: '/check-email'
      path: '/check-email'
      fullPath: '/check-email'
      preLoaderRoute: typeof CheckEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/builder': {
      id: '/builder'
      path: '/builder'
      fullPath: '/builder'
      preLoaderRoute: typeof BuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-us': {
      id: '/about-us'
      path: '/about-us'
      fullPath: '/about-us'
      preLoaderRoute: typeof AboutUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/subscription': {
      id: '/api/subscription'
      path: '/api/subscription'
      fullPath: '/api/subscription'
      preLoaderRoute: typeof ApiSubscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/reconcile-checkout': {
      id: '/api/reconcile-checkout'
      path: '/api/reconcile-checkout'
      fullPath: '/api/reconcile-checkout'
      preLoaderRoute: typeof ApiReconcileCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/portal-session': {
      id: '/api/portal-session'
      path: '/api/portal-session'
      fullPath: '/api/portal-session'
      preLoaderRoute: typeof ApiPortalSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/checkout': {
      id: '/api/checkout'
      path: '/api/checkout'
      fullPath: '/api/checkout'
      preLoaderRoute: typeof ApiCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cancel-subscription': {
      id: '/api/cancel-subscription'
      path: '/api/cancel-subscription'
      fullPath: '/api/cancel-subscription'
      preLoaderRoute: typeof ApiCancelSubscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/billing': {
      id: '/account/billing'
      path: '/billing'
      fullPath: '/account/billing'
      preLoaderRoute: typeof AccountBillingRouteImport
      parentRoute: typeof AccountRoute
    }
    '/api/webhooks/stripe': {
      id: '/api/webhooks/stripe'
      path: '/api/webhooks/stripe'
      fullPath: '/api/webhooks/stripe'
      preLoaderRoute: typeof ApiWebhooksStripeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AccountRouteChildren {
  AccountBillingRoute: typeof AccountBillingRoute
}

const AccountRouteChildren: AccountRouteChildren = {
  AccountBillingRoute: AccountBillingRoute,
}

const AccountRouteWithChildren =
  AccountRoute._addFileChildren(AccountRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutUsRoute: AboutUsRoute,
  AccountRoute: AccountRouteWithChildren,
  BlogRoute: BlogRoute,
  BuilderRoute: BuilderRoute,
  CheckEmailRoute: CheckEmailRoute,
  ContactUsRoute: ContactUsRoute,
  GettingStartedRoute: GettingStartedRoute,
  LogInRoute: LogInRoute,
  PricingCheckoutRoute: PricingCheckoutRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  ProfileRoute: ProfileRoute,
  RoadmapRoute: RoadmapRoute,
  SignUpRoute: SignUpRoute,
  SubscriptionRoute: SubscriptionRoute,
  SupportRoute: SupportRoute,
  TermsOfServiceRoute: TermsOfServiceRoute,
  TutorialsRoute: TutorialsRoute,
  ApiCancelSubscriptionRoute: ApiCancelSubscriptionRoute,
  ApiCheckoutRoute: ApiCheckoutRoute,
  ApiPortalSessionRoute: ApiPortalSessionRoute,
  ApiReconcileCheckoutRoute: ApiReconcileCheckoutRoute,
  ApiSubscriptionRoute: ApiSubscriptionRoute,
  ApiWebhooksStripeRoute: ApiWebhooksStripeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
